// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortalInfoSoftware.Infrastructure.Persistence;

#nullable disable

namespace PortalInfoSoftware.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614195017_ModuloAutenticacion")]
    partial class ModuloAutenticacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortalInfoSoftware.Domain.Entities.Administrador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("PortalInfoSoftware.Domain.Entities.Materia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Competencias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contenidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Creditos")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Objetivos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("PortalInfoSoftware.Domain.Entities.MateriaPrerrequisito", b =>
                {
                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrerrequisitoId")
                        .HasColumnType("uuid");

                    b.HasKey("MateriaId", "PrerrequisitoId");

                    b.HasIndex("PrerrequisitoId");

                    b.ToTable("MateriasPrerrequisitos");
                });

            modelBuilder.Entity("PortalInfoSoftware.Domain.Entities.PlanEstudios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PlanesEstudio");
                });

            modelBuilder.Entity("PortalInfoSoftware.Domain.Entities.Materia", b =>
                {
                    b.HasOne("PortalInfoSoftware.Domain.Entities.PlanEstudios", "PlanEstudios")
                        .WithMany("Materias")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanEstudios");
                });

            modelBuilder.Entity("PortalInfoSoftware.Domain.Entities.MateriaPrerrequisito", b =>
                {
                    b.HasOne("PortalInfoSoftware.Domain.Entities.Materia", "Materia")
                        .WithMany("Prerrequisitos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalInfoSoftware.Domain.Entities.Materia", "Prerrequisito")
                        .WithMany("Habilitadas")
                        .HasForeignKey("PrerrequisitoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Prerrequisito");
                });

            modelBuilder.Entity("PortalInfoSoftware.Domain.Entities.Materia", b =>
                {
                    b.Navigation("Habilitadas");

                    b.Navigation("Prerrequisitos");
                });

            modelBuilder.Entity("PortalInfoSoftware.Domain.Entities.PlanEstudios", b =>
                {
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
