sonar.projectKey=PortalInfoSoftware_Backend
sonar.organization=ucb-software
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/obj/**,**/bin/**,**/Migrations/**,**/Seeders/**
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml